### ISSUE TITLE
Audio does not seem to work with mobile

### ISSUE THREAD

**Issue by caseyyee** [haydenjameslee/networked-aframe#1]
Tried both IOS (on safari) as well as Chrome on a pixel.

Works fine on desktop.

**Comment by haydenjameslee** [comment]
Thanks! I haven't tested audio too much yet. Was this using a local signalling server or a public one on Amazon? If it's public feel free to share the link and I can try to repro. 

We should be able to get more info by connected to the chrome browser

**Comment by haydenjameslee** [comment]
Sorry fat fingers accidentally closed this^

**Comment by caseyyee** [comment]
I was working locally.  Looks like the issue is due to https requiring https.

![image](https://cloud.githubusercontent.com/assets/1560884/24064280/bcad770a-0b20-11e7-8f93-bd88605b0c36.png)

**Comment by haydenjameslee** [comment]
Ah yes this is true. In order to use GetUserMedia with any domain other than localhost you need HTTPS. It's one of the reasons I switched the examples to HTTPS recently.

Note that if you're just using the data channel and not microphone audio then you don't need HTTPS.

When I get around to writing a tutorial on how to host NAF, I'll be including a quick blurb on how to use Certbot to setup free HTTPS quickly.
