### ISSUE TITLE
Support positional audio (based on avatar positions)

### ISSUE THREAD

**Issue by cvan** [haydenjameslee/networked-aframe#11]
It'd be nice to spatialise the audio (via `navigator.getUserMedia`) emitted from the avatars in the 3D space.

/cc @caseyyee.

**Comment by caseyyee** [comment]
Ah yes, this would be nice 👍

**Comment by haydenjameslee** [comment]
+1

I tried to have this ready for launch but couldn't get it working. I'll take a look at it again soon (or feel free to do so yourselves in the meantime). Here's the relevant code: https://github.com/haydenjameslee/networked-aframe/blob/master/src/webrtc_interfaces/EasyRtcInterface.js#L57

**Comment by nitins1** [comment]
Where exactly is the "relevant code"? @haydenjameslee

**Comment by haydenjameslee** [comment]
Sorry file name changed. @nitins1 check out the `connectWithAudio` function here: https://github.com/haydenjameslee/networked-aframe/blob/master/src/network_interfaces/EasyRtcInterface.js

**Comment by machenmusik** [comment]
So I did what should have worked but the webrtc audio source refused to be capitalized by the PannerNode.  As a sanity check, I replaced the webrtc audio source with a test ogg file and that worked fine... but not entirely helpful at the moment. (Both Chrome and Firefox on Windows)

**Comment by delapuente** [comment]
As soon as aframevr/aframe#3042 is merged you will be able to do it.

**Comment by haydenjameslee** [comment]
Awesome! Thanks for the heads up @delapuente

**Comment by netpro2k** [comment]
Started taking a look at this here: https://github.com/netpro2k/networked-aframe/tree/feature/positional-audio

Kind of just patched it in in the simplest way possible. Not sure if anyone has thoughts about how these audio streams should be exposed by the adapter, or how the streams should be associated with entities.

Also created a `networked-audio-source` that handles what aframevr/aframe#3042 will do. This might go away later or simply just set up a `sound` component.

I experimented with using https://github.com/google/songbird as well for the audio instead of `PannerNode`, though this is far less thought out https://github.com/netpro2k/networked-aframe/blob/1aa3cd0bd733df9117f2e0765d0881e69baf6303/src/components/media-stream-sound.js#L31-L135

**Comment by machenmusik** [comment]
on mobile Chrome, I don't hear any audio when using the networked-audio-source.  I wonder if it may be due to user gesture requirements for media playback when there is no associated governing audio element

**Comment by robertlong** [comment]
@machenmusik what OS are you on? I've had issues on iOS 11 which has WebRTC support. It worked on Android though. Haven't pinned down the issue yet.

**Comment by machenmusik** [comment]
@robertlong This was on my S8 with Nougat, using mobile Chrome.  I found that I couldn't just use the stream, I had to create an audio element with srcObject and then do the createMediaStreamSource and setNodeSource.

**Comment by machenmusik** [comment]
I have to say, the positional audio doesn't sounds as good as I would like or expect... either with voice, or by using SoundFlower to pump in prerecorded audio... not sure if that is overcompression by WebRTC, or the default spatialization from THREE, or a combination of both.

**Comment by rm8x** [comment]
Looks like THREE's PositionalAudio does not make use of HRTF.  Should be easy to add and should improve quality. Songbird does but not familiar enough with it to know if it is appropriate for streaming as it uses Omnitone to generate ambisonics.
