### ISSUE TITLE
Port ranges for WebRTC

### ISSUE THREAD

**Issue by HAZARDU5** [haydenjameslee/networked-aframe#14]
I've been playing around with getting the server running on an Ubuntu 16.04 VPS and am using `iptables` to manage firewalling. Just wondering what port ranges I should open up as it doesn't seem to want to allow connections from the client -> server if only ports 80, 443 and 8080 are open. I assume it's a problem with the STUN/TURN connection from the server to Google's servers. Do I just need to leave the higher ranges open? Is there any point restricting ports if this is the case?

**Comment by haydenjameslee** [comment]
WebRTC can have a hard time with firewalls. I'll refer to other sources to explain the problems so as not to confuse / get it wrong, but the overall problem can generally be solved by using STUN and/or TURN servers. Check out https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/ for an explanation.

Try using `https://haydenlee.io` as your `signalUrl` as explained here: https://github.com/haydenjameslee/networked-aframe#scene-component and see if that fixes it. I've setup that server to use XirSys which is a service to provide STUN and TURN. Note that since my site is https you'll need to be hosting on an HTTPS-enabled server.

If that doesn't work there might be another issue.

**Comment by HAZARDU5** [comment]
I ended up switching to using DigitalOcean's firewall that sits in front of my instance instead of `iptables` and it seems to work correctly now. I think we can close this.
